name: HTML Validation CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-html:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate HTML files
        uses: Cyb3r-Jak3/html5validator@v0.9.0
        with:
          root: ./